---
abstract: 'Read and write INI-style config files with structure extensions'
author:
  - 'Anthony Kilna <anthony@kilna.com>'
build_requires:
  File::Temp: 0
  FindBin: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-INIPlus
provides:
  Config::INIPlus:
    file: lib/Config/INIPlus.pm
    version: v1.0.2
requires:
  Carp: 0
  IO::File: 0
  IO::String: 0
  Scalar::Util: 0
  perl: v5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: v1.0.2
